// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthConfigData, AuthConfigResponses, CompleteChallengeData, CompleteChallengeErrors, CompleteChallengeResponses, CreateAuthTokenData, CreateAuthTokenErrors, CreateAuthTokenResponses, DeleteAuthTokenData, DeleteAuthTokenErrors, DeleteAuthTokenResponses, DeleteCustomDomainData, DeleteCustomDomainErrors, DeleteCustomDomainResponses, DeleteTunnelData, DeleteTunnelErrors, DeleteTunnelResponses, GetAuthTokenData, GetAuthTokenErrors, GetAuthTokenResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetCustomDomainData, GetCustomDomainErrors, GetCustomDomainResponses, GetLocalupMetricsData, GetLocalupMetricsErrors, GetLocalupMetricsResponses, GetRequestData, GetRequestErrors, GetRequestResponses, GetTunnelData, GetTunnelErrors, GetTunnelResponses, HealthCheckData, HealthCheckResponses, InitiateChallengeData, InitiateChallengeErrors, InitiateChallengeResponses, ListAuthTokensData, ListAuthTokensErrors, ListAuthTokensResponses, ListCustomDomainsData, ListCustomDomainsErrors, ListCustomDomainsResponses, ListRequestsData, ListRequestsErrors, ListRequestsResponses, ListTcpConnectionsData, ListTcpConnectionsErrors, ListTcpConnectionsResponses, ListTunnelsData, ListTunnelsErrors, ListTunnelsResponses, ListUserTeamsData, ListUserTeamsErrors, ListUserTeamsResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RegisterData, RegisterErrors, RegisterResponses, ReplayRequestData, ReplayRequestErrors, ReplayRequestResponses, UpdateAuthTokenData, UpdateAuthTokenErrors, UpdateAuthTokenResponses, UploadCustomDomainData, UploadCustomDomainErrors, UploadCustomDomainResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List user's auth tokens
 */
export const listAuthTokens = <ThrowOnError extends boolean = false>(options?: Options<ListAuthTokensData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListAuthTokensResponses, ListAuthTokensErrors, ThrowOnError>({
        url: '/api/auth-tokens',
        ...options
    });
};

/**
 * Create a new auth token (API key for tunnel authentication)
 */
export const createAuthToken = <ThrowOnError extends boolean = false>(options: Options<CreateAuthTokenData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateAuthTokenResponses, CreateAuthTokenErrors, ThrowOnError>({
        url: '/api/auth-tokens',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete (revoke) an auth token
 */
export const deleteAuthToken = <ThrowOnError extends boolean = false>(options: Options<DeleteAuthTokenData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteAuthTokenResponses, DeleteAuthTokenErrors, ThrowOnError>({
        url: '/api/auth-tokens/{id}',
        ...options
    });
};

/**
 * Get specific auth token details
 */
export const getAuthToken = <ThrowOnError extends boolean = false>(options: Options<GetAuthTokenData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAuthTokenResponses, GetAuthTokenErrors, ThrowOnError>({
        url: '/api/auth-tokens/{id}',
        ...options
    });
};

/**
 * Update auth token (name, description, or active status)
 */
export const updateAuthToken = <ThrowOnError extends boolean = false>(options: Options<UpdateAuthTokenData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdateAuthTokenResponses, UpdateAuthTokenErrors, ThrowOnError>({
        url: '/api/auth-tokens/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get authentication configuration
 */
export const authConfig = <ThrowOnError extends boolean = false>(options?: Options<AuthConfigData, ThrowOnError>) => {
    return (options?.client ?? client).get<AuthConfigResponses, unknown, ThrowOnError>({
        url: '/api/auth/config',
        ...options
    });
};

/**
 * Login with email and password
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: '/api/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Logout (clear session cookie)
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
        url: '/api/auth/logout',
        ...options
    });
};

/**
 * Get current authenticated user
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
        url: '/api/auth/me',
        ...options
    });
};

/**
 * Register a new user
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
        url: '/api/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all custom domains
 */
export const listCustomDomains = <ThrowOnError extends boolean = false>(options?: Options<ListCustomDomainsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListCustomDomainsResponses, ListCustomDomainsErrors, ThrowOnError>({
        url: '/api/domains',
        ...options
    });
};

/**
 * Upload a custom domain certificate
 */
export const uploadCustomDomain = <ThrowOnError extends boolean = false>(options: Options<UploadCustomDomainData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadCustomDomainResponses, UploadCustomDomainErrors, ThrowOnError>({
        url: '/api/domains',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Complete/verify ACME challenge
 */
export const completeChallenge = <ThrowOnError extends boolean = false>(options: Options<CompleteChallengeData, ThrowOnError>) => {
    return (options.client ?? client).post<CompleteChallengeResponses, CompleteChallengeErrors, ThrowOnError>({
        url: '/api/domains/challenge/complete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Initiate ACME challenge for a domain
 */
export const initiateChallenge = <ThrowOnError extends boolean = false>(options: Options<InitiateChallengeData, ThrowOnError>) => {
    return (options.client ?? client).post<InitiateChallengeResponses, InitiateChallengeErrors, ThrowOnError>({
        url: '/api/domains/challenge/initiate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a custom domain
 */
export const deleteCustomDomain = <ThrowOnError extends boolean = false>(options: Options<DeleteCustomDomainData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteCustomDomainResponses, DeleteCustomDomainErrors, ThrowOnError>({
        url: '/api/domains/{domain}',
        ...options
    });
};

/**
 * Get a specific custom domain
 */
export const getCustomDomain = <ThrowOnError extends boolean = false>(options: Options<GetCustomDomainData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCustomDomainResponses, GetCustomDomainErrors, ThrowOnError>({
        url: '/api/domains/{domain}',
        ...options
    });
};

/**
 * Health check endpoint
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};

/**
 * List captured requests (traffic inspector)
 */
export const listRequests = <ThrowOnError extends boolean = false>(options?: Options<ListRequestsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListRequestsResponses, ListRequestsErrors, ThrowOnError>({
        url: '/api/requests',
        ...options
    });
};

/**
 * Get a specific captured request
 */
export const getRequest = <ThrowOnError extends boolean = false>(options: Options<GetRequestData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRequestResponses, GetRequestErrors, ThrowOnError>({
        url: '/api/requests/{id}',
        ...options
    });
};

/**
 * Replay a captured request
 */
export const replayRequest = <ThrowOnError extends boolean = false>(options: Options<ReplayRequestData, ThrowOnError>) => {
    return (options.client ?? client).post<ReplayRequestResponses, ReplayRequestErrors, ThrowOnError>({
        url: '/api/requests/{id}/replay',
        ...options
    });
};

/**
 * List captured TCP connections (traffic inspector)
 */
export const listTcpConnections = <ThrowOnError extends boolean = false>(options?: Options<ListTcpConnectionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListTcpConnectionsResponses, ListTcpConnectionsErrors, ThrowOnError>({
        url: '/api/tcp-connections',
        ...options
    });
};

/**
 * Get user's teams
 */
export const listUserTeams = <ThrowOnError extends boolean = false>(options?: Options<ListUserTeamsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListUserTeamsResponses, ListUserTeamsErrors, ThrowOnError>({
        url: '/api/teams',
        ...options
    });
};

/**
 * List all tunnels (active and optionally inactive)
 */
export const listTunnels = <ThrowOnError extends boolean = false>(options?: Options<ListTunnelsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListTunnelsResponses, ListTunnelsErrors, ThrowOnError>({
        url: '/api/tunnels',
        ...options
    });
};

/**
 * Delete a tunnel
 */
export const deleteTunnel = <ThrowOnError extends boolean = false>(options: Options<DeleteTunnelData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteTunnelResponses, DeleteTunnelErrors, ThrowOnError>({
        url: '/api/tunnels/{id}',
        ...options
    });
};

/**
 * Get a specific tunnel by ID
 */
export const getTunnel = <ThrowOnError extends boolean = false>(options: Options<GetTunnelData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTunnelResponses, GetTunnelErrors, ThrowOnError>({
        url: '/api/tunnels/{id}',
        ...options
    });
};

/**
 * Get tunnel metrics
 */
export const getLocalupMetrics = <ThrowOnError extends boolean = false>(options: Options<GetLocalupMetricsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetLocalupMetricsResponses, GetLocalupMetricsErrors, ThrowOnError>({
        url: '/api/tunnels/{id}/metrics',
        ...options
    });
};
